### PR TITLE
create github-workflow

### PR DESCRIPTION
**Pull request by jenweber**

### CODE REVIEW

**Comment by jenweber** [comment]
@MelSumner good idea. I have added a sentence or two on requesting reviews from lead maintainers. What do you think?

**Comment by MelSumner** [comment]
@jenweber yes, this looks great!

**Comment by jenweber** [comment]
@kennethlarsen that's right

**Comment by locks** [comment]
If we are telling people to do admin merges for insignificant changes we might as well remove that check.

**Comment by MelSumner** [comment]
@locks I don’t know-we want it there for most changes. It’s a small sub-set of improvements that we should all be able to make without a fuss.

**Pull request merged**
