### PR TITLE
Create meeting notes process doc

### PR DESCRIPTION
**Pull request by jenweber**
I think we should make our public meeting notes public in [GitHub](https://github.com/emberjs/core-notes/tree/master/learning-team) by taking them directly there, instead of Notion. This PR describes that plan. It does not propose making past notes/folders public, nor does it prohibit taking private notes as-needed.

[Rendered](https://github.com/ember-learn/handbook/blob/public-meeting-notes/meeting-notes.md)

**Some data to back up this proposal**
In the past 6 months, there theoretically should have been about 20-25 PRs to add the [learning team notes on GitHub](https://github.com/emberjs/core-notes/tree/master/learning-team). Instead, there are 4. Since everyone on the team is having trouble following through, this is an indicator that the process isn't working for us, and we should adapt. We tend to backfill missing things (thanks to locks, lately), so the notes do eventually make it in. With this change, we eliminate that time gap. We give up some concurrent-editing capabilities but I think the tradeoff is worthwhile.

### CODE REVIEW

**Comment by abhilashlr** [comment]
Very much in favour. 

> What happens as notes URLs change?
> 
> They will break over time, since we are not in direct control over these URLs. We accept the tradeoff of easy short term access for immediate community interactions over having long-term reference within Notion. Our long term reference must remain GitHub.
> 

If the expiration links are a concern, a part of it can be mitigated through short URL providers. Perhaps, there too, there is a chance that "they" might also break over time. Just a thought.

**Comment by jenweber** [comment]
@mansona thanks for your comments and willingness to give this a try. My thinking is that today, all our meetings except about 2-3 per year are open to the whole community to listen to in real time, and so it's natural that our notes are also available in real time. Needing to read and filter notes for potentially private links and such before posting to GitHub is part of what slows us down, so my hope is that it would be even easier for us to place notes in their long-term homes. I would like to be able to safely export all md files and upload them in one go if we get behind. We would continue to maintain private folders for anything we need them for, and would not try to move old content into the new public space.

Our stable URLs for notes long-term would continue to be the GitHub notes repo. Notion brings a benefit of searchable notes that we don't have in GitHub, so I think both serve an important purpose in our process.

**Comment by jenweber** [comment]
@mansona I added a note after reflecting on your comments:

```
At the discretion of the Learning Team, some meetings may still have private notes. This should be rare.
```

I think each year we've had about 3 closed meetings, out of 50. This addition now accounts for us to have that same flexibility.

**Comment by MelSumner** [comment]
I'm on other open source committees, and we take notes directly in GitHub as we conduct the meeting. This is probably my favorite approach of all the ones I've seen so far- I prefer depending on more platforms than we need to.

**Comment by jenweber** [comment]
@MelSumner do you remember why we didn’t go that route before, instead of using Notion? I don’t remember details. But my thinking is that since we regularly have multiple people editing in real time, we should maybe preserve that ability. Using GitHub-only in real time would achieve my own goals if there is support for it.

**Comment by mansona** [comment]
Github-only would also satisfy my concerns 🎉

**Comment by jenweber** [comment]
Is there anyone who would prefer Notion over the GitHub-only approach? Otherwise, I will rework this to be centered on GitHub instead. I think it would significantly change how we take notes and form agendas, but I'm game to try it.

**Comment by jenweber** [comment]
I have substantially modified this PR to suggest taking notes directly in GitHub. Please re-review and comment. Thank you!

**Comment by jenweber** [comment]
Since we started doing this process this week, and there seems to be consensus on it, I'm merging this. Let's reevaluate in 4 weeks if it's working for us, and make adjustments as needed!

**Pull request merged**
